### ISSUE TITLE
not working on catalina

### ISSUE THREAD

**Issue by ElegantSoft** [xqin/keyboard_leds#1]
I tried on 10.15.2
Failed to copy cookies.\n

**Comment by xqin** [comment]
I just tested it, and the code works.

OS Version:  10.15.4 (19E287)

**Comment by ElegantSoft** [comment]
![keyboard_leds — apple@apples — -zsh — 80×24 2020-08-17 12-14-49](https://user-images.githubusercontent.com/47436634/90385370-520ad280-e083-11ea-8fc1-6bb413e00360.png)
this is the output for me any hints ?

**Comment by xqin** [comment]
remove sudo from command line.

this  tool  dosn't need root permission.
